### ISSUE TITLE
Hi trying to copy this in 2020

### ISSUE THREAD

**Issue by AnonymousAnonymity** [lindehaven/Raspberry#1]
Hi, first time doing anything like this. I'm not sure what has change in the 2 years but the connection I try to make in the py script or php stops every time at the 

       $conn = new mysqli($servername, $username, $password, $dbname);
       if ($conn->connect_error) {
         echo "<table><tbody><tr class='val'><td>N/A</td></tr></tbody></table>";
         die();
       }

Nothing after this will work I've put a echo test in about everywhere after this including before the if statement but line 58 seems to kill everything else. So when I pull up the index site on my computer I get the time and nothing after including the footers or anything else. I've looked at everything I can but have been stuck for 2 nights now and though I'd sign up and ask for some help.

I also move the cpu temp up and it would work if put above that mysqli statement.

Ideas?

**Comment by lindehaven** [comment]
Hi,

I haven't used my RPI for this in over a year so I cannot test myself. So I'll give you my best guess.

You wrote that "it would work if put above that mysqli statement". I'm not sure what You mean by that. You can surely get a web page but that would not display correct temperatures because they are supposed to be fetched from the Maria DB.

I suspect that Your Maria DB is not setup properly or that You use incorrect username/password for it.

- To begin with, You have to setup a Maria DB, see 'raspbian_maria_db_setup.md'. Set the username and password that you want.

- Ensure that You set the user, passwd and db accordingly in 'temperature_logger.py' on line 12.

- Ensure that You set the $servername, $username, $password and $dbname accordingly in 'index.php' on lines 37-40.

Hope that this can help You get Your system running.

Regards, Lars

**Comment by AnonymousAnonymity** [comment]
I'm amazed to get an answer, so first thank you.

I followed that all exactly I'm trying to pin down what about the $conn = new mysqli is an issue. 
I have the same password and username and DB as is working in the temperature_logger.py. every 5 minutes I have a logged temp in the temperature table so I have 300 plus lines to work with.

I suspect it's something to do with the permissions in the mariadb so I've been trying to grant any permission I can till I hit the right one.

The biggest reason I'm sure it is something to do with this exactly. I can put a echo and get a statement from the line about the mysqli line but the line after I don't get anything even if it's before the following if statement.

**Comment by AnonymousAnonymity** [comment]
YES I finally figured it out!!!!
the php or apache listed is depreciated so :

sudo apt-get install php-mysql
sudo service apache2 restart

PHP 7 needs the mysql stuff to work

**Comment by lindehaven** [comment]
Thanks for the feedback. When I come around to it, which may never happen, I will update the code and instructions to something more contemporary.

**Comment by AnonymousAnonymity** [comment]
I do have a couple questions.

What program did you or do you use to write the php code and I guess the
same for the python. I don't have anythign perfered yet.

I started with your guide because I was making sure I can incrementially
step up what I was doing I started with a guide for just getting the temp
gage working My first dh11 burned out so I went to a water proof one and
then I went on to this sensor. Your project is the next step because it
logs the info which will allow me to move on to graphing it and then I am
going to move on to text or email notifications when the temp is out of
spec for a setable length of time and then I hope to expand it to multiple
points in the same db. There's plenty of guides I found for the ned result
but all of them want you to use there paid db on their servers and yours
was the first to put it all together on a zero so it is the most cost
effective because I'm looking at $15 to make each point (cost using extra
parts I already have lasying around $10 for pi zerowh and hopefully $5 for
the dht22 in the end)

Again thanks

**Comment by lindehaven** [comment]
I've been using emacs for as long as I can remember, mostly on Unix and Linux both also on Windows. But I believe that I used notepad++ when I wrote this code. I still use notepad++ on Windows but also Atom. I'm kind of old fashioned and prefer robust development environments instead of bulky and buggy ones (read Eclipse).
